# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('clientlattude', models.CharField(max_length=100)),
                ('clientlogitute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DriverJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True, default='No Instructions', max_length=500)),
                ('isdelivered', models.BooleanField(default=False)),
                ('timeofdelivery', models.DateTimeField(auto_now_add=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directme.Client')),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directme.Driver')),
            ],
        ),
    ]
